"use client";

import * as React from "react";
import { notFound, useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { getScheme } from "@/lib/db/store";
import type { SchemeOfWork } from "@/lib/types";
import { formatDate } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ExportToolbar } from "@/components/export/export-toolbar";
import { downloadSchemeDocx } from "@/lib/export/docx";
import { downloadSchemePdf } from "@/lib/export/pdf";

export function SchemeView({ id }: { id: string }) {
  const router = useRouter();
  const [scheme, setScheme] = React.useState<SchemeOfWork | null>(null);
  const [ready, setReady] = React.useState(false);

  React.useEffect(() => {
    getScheme(id).then((s) => {
      setScheme(s || null);
      setReady(true);
    });
  }, [id]);

  if (!ready) return null;
  if (!scheme) return notFound();

  return (
    <div className="space-y-6">
      <div className="no-print flex flex-wrap items-center justify-between gap-3">
        <Button variant="ghost" size="sm" onClick={() => router.push("/library")}>
          <ArrowLeft className="h-4 w-4" /> Library
        </Button>
        <ExportToolbar onWord={() => downloadSchemeDocx(scheme)} onPdf={() => downloadSchemePdf(scheme)} />
      </div>

      <div className="print-page space-y-4">
        <div>
          <h1 className="text-xl font-bold sm:text-2xl">{scheme.title}</h1>
          <div className="mt-2 flex flex-wrap gap-2">
            <Badge variant="secondary">{scheme.subject}</Badge>
            <Badge variant="secondary">{scheme.gradeLevel}</Badge>
            <Badge variant="secondary">{scheme.strand}</Badge>
            <Badge variant="secondary">{scheme.term} {scheme.year}</Badge>
            <Badge variant="secondary">{scheme.durationWeeks} weeks</Badge>
            <Badge variant={scheme.llmSource === "ai" ? "success" : "outline"}>
              {scheme.llmSource === "ai" ? "AI generated" : "Offline template"}
            </Badge>
            <span className="text-xs text-muted-foreground">Created {formatDate(scheme.createdAt)}</span>
          </div>
        </div>

        <Card>
          <CardContent className="overflow-x-auto p-0">
            <table className="w-full min-w-[900px] text-left text-xs">
              <thead>
                <tr className="border-b bg-primary/5">
                  <th className="px-3 py-2 font-semibold">Week</th>
                  <th className="px-3 py-2 font-semibold">Lesson</th>
                  <th className="px-3 py-2 font-semibold">Sub-topic</th>
                  <th className="px-3 py-2 font-semibold">Learning Outcomes</th>
                  <th className="px-3 py-2 font-semibold">Key Inquiry Questions</th>
                  <th className="px-3 py-2 font-semibold">Activities</th>
                  <th className="px-3 py-2 font-semibold">Resources</th>
                  <th className="px-3 py-2 font-semibold">Assessment</th>
                </tr>
              </thead>
              <tbody>
                {scheme.rows.map((r) => (
                  <tr key={r.lessonNumber} className="border-b align-top">
                    <td className="px-3 py-2">{r.week}</td>
                    <td className="px-3 py-2">{r.lessonNumber}</td>
                    <td className="px-3 py-2 font-medium">{r.subtopic}</td>
                    <td className="px-3 py-2"><List values={r.learningOutcomes} /></td>
                    <td className="px-3 py-2"><List values={r.keyInquiryQuestions} /></td>
                    <td className="px-3 py-2"><List values={r.learningActivities} /></td>
                    <td className="px-3 py-2"><List values={r.resources} /></td>
                    <td className="px-3 py-2"><List values={r.assessment} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </CardContent>
        </Card>
      </div>

      <div className="no-print flex items-center justify-between">
        <p className="text-xs text-muted-foreground">Generated by SmartTeacher — review and adapt to your learners.</p>
      </div>
    </div>
  );
}

function List({ values }: { values: string[] }) {
  return (
    <ul className="list-disc space-y-0.5 pl-4">
      {values.map((v, i) => (
        <li key={i}>{v}</li>
      ))}
    </ul>
  );
}